ALTER TABLE users ADD COLUMN availability VARCHAR(20) DEFAULT 'AVAILABLE';
ALTER TABLE users ADD COLUMN location VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN daily_wage DECIMAL(10,2) NULL;
ALTER TABLE users ADD COLUMN languages VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN business_name VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN verified BOOLEAN DEFAULT FALSE;
