-- Reset all demo account passwords to "password123"
-- BCrypt hash for "password123" (generated by the app itself)
UPDATE users SET password='$2a$12$c0r9C/g/Nlz6IUcjXaN18.zOOwGA98q3x79ikzERuTuGnh1NcyZp2' WHERE phone LIKE '987654320%' OR phone LIKE '9800000%';
SELECT phone, LEFT(password,10) as hash_check FROM users WHERE phone IN ('9876543201','9800000001');
